countries = {
    'AF': 'Afghanistan',
    'AX': 'Akrotiri Sovereign Base Area',
    'AL': 'Albania',
    'AG': 'Algeria',
    'AQ': 'American Samoa',
    'AN': 'Andorra',
    'AO': 'Angola',
    'AV': 'Anguilla',
    'AY': 'Antarctica',
    'AC': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AA': 'Aruba',
    'AT': 'Ashmore and Cartier Islands',
    'AS': 'Australia',
    'AU': 'Austria',
    'AJ': 'Azerbaijan',
    'BF': 'Bahamas, The',
    'BA': 'Bahrain',
    'FQ': 'Baker Island',
    'BG': 'Bangladesh',
    'BB': 'Barbados',
    'BS': 'Bassas da India',
    'BO': 'Belarus',
    'BE': 'Belgium',
    'BH': 'Belize',
    'BN': 'Benin',
    'BD': 'Bermuda',
    'BT': 'Bhutan',
    'BL': 'Bolivia',
    'BK': 'Bosnia-Herzegovina',
    'BC': 'Botswana',
    'BV': 'Bouvet Island',
    'BR': 'Brazil',
    'IO': 'British Indian Ocean Territory',
    'VI': 'British Virgin Islands',
    'BX': 'Brunei',
    'BU': 'Bulgaria',
    'UV': 'Burkina Faso',
    'BY': 'Burundi',
    'CB': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CV': 'Cape Verde',
    'CJ': 'Cayman Islands',
    'CT': 'Central African Republic',
    'CD': 'Chad',
    'CI': 'Chile',
    'CH': 'China',
    'KT': 'Christmas Island',
    'IP': 'Clipperton Island',
    'CK': 'Cocos Keeling Islands',
    'CO': 'Colombia',
    'CN': 'Comoros',
    'CF': 'Congo',
    'CW': 'Cook Islands',
    'CR': 'Coral Sea Islands',
    'CS': 'Costa Rica',
    'IV': 'Cote dIvoire',
    'HR': 'Croatia',
    'CU': 'Cuba',
    'CY': 'Cyprus',
    'EZ': 'Czech Republic',
    'LO': 'Czechoslovakia',
    'CG': 'Democratic Republic of the Congo',
    'DA': 'Denmark',
    'DX': 'Dhekelia Sovereign Base Area',
    'DJ': 'Djibouti',
    'DO': 'Dominica',
    'DR': 'Dominican Republic',
    'TT': 'East Timor',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'ES': 'El Salvador',
    'GV': 'Equatorial Guinea',
    'EK': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EN': 'Estonia',
    'ET': 'Ethiopia',
    'PJ': 'Etorofu, Habomai, Kunashiri and Shikotan Islands',
    'EU': 'Europa Island',
    'FK': 'Falkland Islands Islas Malvinas',
    'FO': 'Faroe Islands',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'FG': 'French Guiana',
    'FP': 'French Polynesia',
    'FS': 'French Southern and Antarctic Lands',
    'GB': 'Gabon',
    'GA': 'Gambia',
    'GZ': 'Gaza Strip',
    'GG': 'Georgia',
    'GM': 'Germany',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GO': 'Glorioso Islands',
    'GR': 'Greece',
    'GL': 'Greenland',
    'GJ': 'Grenada',
    'GP': 'Guadeloupe',
    'GQ': 'Guam',
    'GT': 'Guatemala',
    'GK': 'Guernsey',
    'PU': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HA': 'Haiti',
    'HM': 'Heard Island and McDonald Islands',
    'HO': 'Honduras',
    'HK': 'Hong Kong',
    'HQ': 'Howland Island',
    'HU': 'Hungary',
    'IC': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran',
    'IZ': 'Iraq',
    'EI': 'Ireland',
    'IM': 'Isle of Man',
    'IS': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JN': 'Jan Mayen',
    'JA': 'Japan',
    'DQ': 'Jarvis Island',
    'JE': 'Jersey',
    'JQ': 'Johnston Atoll',
    'JO': 'Jordan',
    'JU': 'Juan de Nova Island',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KQ': 'Kingman Reef',
    'KR': 'Kiribati',
    'KV': 'Kosovo',
    'KU': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Laos',
    'LG': 'Latvia',
    'LE': 'Lebanon',
    'LT': 'Lesotho',
    'LI': 'Liberia',
    'LY': 'Libya',
    'LS': 'Liechtenstein',
    'LH': 'Lithuania',
    'LU': 'Luxembourg',
    'MC': 'Macau',
    'MK': 'Macedonia',
    'MA': 'Madagascar',
    'MI': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'RM': 'Marshall Islands',
    'MB': 'Martinique',
    'MR': 'Mauritania',
    'MP': 'Mauritius',
    'MF': 'Mayotte',
    'MX': 'Mexico',
    'FM': 'Micronesia',
    'MQ': 'Midway Islands',
    'MD': 'Moldova',
    'MN': 'Monaco',
    'MG': 'Mongolia',
    'MJ': 'Montenegro',
    'MH': 'Montserrat',
    'MO': 'Morocco',
    'MZ': 'Mozambique',
    'BM': 'Myanmar',
    'WA': 'Namibia',
    'NR': 'Nauru',
    'BQ': 'Navassa Island',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NT': 'Netherlands Antilles',
    'NC': 'New Caledonia',
    'NZ': 'New Zealand',
    'NU': 'Nicaragua',
    'NG': 'Niger',
    'NI': 'Nigeria',
    'NE': 'Niue',
    'NM': 'No Mans Land',
    'NF': 'Norfolk Island',
    'KN': 'North Korea',
    'CQ': 'Northern Mariana Islands',
    'NO': 'Norway',
    'OS': 'Oceans',
    'MU': 'Oman',
    'PK': 'Pakistan',
    'PS': 'Palau',
    'LQ': 'Palmyra Atoll',
    'PM': 'Panama',
    'PP': 'Papua New Guinea',
    'PF': 'Paracel Islands',
    'PA': 'Paraguay',
    'PE': 'Peru',
    'RP': 'Philippines',
    'PC': 'Pitcairn Islands',
    'PL': 'Poland',
    'PO': 'Portugal',
    'RQ': 'Puerto Rico',
    'QA': 'Qatar',
    'RE': 'Reunion',
    'RO': 'Romania',
    'RS': 'Russia',
    'RW': 'Rwanda',
    'SH': 'Saint Helena',
    'SC': 'Saint Kitts and Nevis',
    'ST': 'Saint Lucia',
    'RN': 'Saint Martin',
    'SB': 'Saint Pierre and Miquelon',
    'VC': 'Saint Vincent and the Grenadines',
    'TB': 'Saint-Barthelemy Island',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'TP': 'Sao Tome and Principe',
    'SA': 'Saudi Arabia',
    'SG': 'Senegal',
    'RI': 'Serbia',
    'SE': 'Seychelles',
    'SL': 'Sierra Leone',
    'SN': 'Singapore',
    'SI': 'Slovenia',
    'BP': 'Solomon Islands',
    'SO': 'Somalia',
    'SF': 'South Africa',
    'SX': 'South Georgia and the South Sandwich Islands',
    'KS': 'South Korea',
    'OD': 'South Sudan',
    'SP': 'Spain',
    'PG': 'Spratly Islands',
    'CE': 'Sri Lanka',
    'SU': 'Sudan',
    'NS': 'Suriname',
    'SV': 'Svalbard',
    'WZ': 'Swaziland',
    'SW': 'Sweden',
    'SZ': 'Switzerland',
    'SY': 'Syria',
    'TW': 'Taiwan',
    'TI': 'Tajikistan',
    'TZ': 'Tanzania',
    'TH': 'Thailand',
    'TO': 'Togo',
    'TL': 'Tokelau',
    'TN': 'Tonga',
    'TD': 'Trinidad and Tobago',
    'TE': 'Tromelin Island',
    'TS': 'Tunisia',
    'TU': 'Turkey',
    'TX': 'Turkmenistan',
    'TK': 'Turks and Caicos Islands',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UP': 'Ukraine',
    'UF': 'Undersea Features',
    'UU': 'Undesignated Sovereignty',
    'AE': 'United Arab Emirates',
    'UK': 'United Kingdom',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'NH': 'Vanuatu',
    'VT': 'Vatican City',
    'VE': 'Venezuela',
    'VM': 'Vietnam, Democratic Republic of',
    'VQ': 'Virgin Islands',
    'WQ': 'Wake Island',
    'WF': 'Wallis and Futuna',
    'WE': 'West Bank',
    'WI': 'Western Sahara',
    'YM': 'Yemen',
    'ZA': 'Zambia',
    'ZI': 'Zimbabwe',
}

languages = {
    "afr": "Afrikaans",
    "sqi": "Albanian",
    "ara": "Arabic",
    "hye": "Armenian",
    "axe": "Azerbaijani",
    "ben": "Bengali",
    "bos": "Bosnian",
    "bul": "Bulgarian",
    "cat": "Catalan",
    "zho": "Chinese",
    "hrv": "Croatian",
    "ces": "Czech",
    "dan": "Danish",
    "nld": "Dutch",
    "est": "Estonian",
    "fin": "Finnish",
    "fra": "French",
    "glg": "Galician",
    "kat": "Georgian",
    "deu": "German",
    "ell": "Greek",
    "guj": "Gujarati",
    "heb": "Hebrew",
    "hin": "Hindi",
    "hun": "Hungarian",
    "isl": "Icelandic",
    "ind": "Indonesian",
    "ita": "Italian",
    "jpn": "Japanese",
    "kan": "Kannada",
    "kaz": "Kazakh",
    "kor": "Korean",
    "lav": "Latvian",
    "lit": "Lithuanian",
    "mkd": "Macedonian",
    "msa": "Malay",
    "mal": "Malayalam",
    "mar": "Marathi",
    "mon": "Mongolian",
    "nep": "Nepali",
    "nor": "Norwegian",
    "nno": "NorwegianNynorsk",
    "fas": "Persian",
    "pol": "Polish",
    "por": "Portuguese",
    "pan": "Punjabi",
    "ron": "Romanian",
    "rus": "Russian",
    "srp": "Serbian",
    "sin": "Sinhalese",
    "slk": "Slovak",
    "slv": "Slovenian",
    "som": "Somali",
    "spa": "Spanish",
    "swa": "Swahili",
    "swe": "Swedish",
    "tam": "Tamil",
    "tel": "Telugu",
    "tha": "Thai",
    "bod": "Tibetan",
    "tur": "Turkish",
    "ukr": "Ukrainian",
    "urd": "Urdu",
    "vie": "Vietnamese",
    "eng": "English"
}

languages_alpha2 = {
    'Afar': 'aa',
    'Abkhazian': 'ab',
    'Avestan': 'ae',
    'Afrikaans': 'af',
    'Akan': 'ak',
    'Amharic': 'am',
    'Aragonese': 'an',
    'Arabic': 'ar',
    'Assamese': 'as',
    'Avaric': 'av',
    'Aymara': 'ay',
    'Azerbaijani': 'az',
    'Bashkir': 'ba',
    'Belarusian': 'be',
    'Bulgarian': 'bg',
    'Bihari languages': 'bh',
    'Bislama': 'bi',
    'Bambara': 'bm',
    'Bengali': 'bn',
    'Tibetan': 'bo',
    'Breton': 'br',
    'Bosnian': 'bs',
    'Catalan; Valencian': 'ca',
    'Chechen': 'ce',
    'Chamorro': 'ch',
    'Corsican': 'co',
    'Cree': 'cr',
    'Czech': 'cs',
    'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': 'cu',
    'Chuvash': 'cv',
    'Welsh': 'cy',
    'Danish': 'da',
    'German': 'de',
    'Divehi; Dhivehi; Maldivian': 'dv',
    'Dzongkha': 'dz',
    'Ewe': 'ee',
    'Greek, Modern (1453-)': 'el',
    'English': 'en',
    'Esperanto': 'eo',
    'Spanish; Castilian': 'es',
    'Estonian': 'et',
    'Basque': 'eu',
    'Persian': 'fa',
    'Fulah': 'ff',
    'Finnish': 'fi',
    'Fijian': 'fj',
    'Faroese': 'fo',
    'French': 'fr',
    'Western Frisian': 'fy',
    'Irish': 'ga',
    'Gaelic; Scottish Gaelic': 'gd',
    'Galician': 'gl',
    'Guarani': 'gn',
    'Gujarati': 'gu',
    'Manx': 'gv',
    'Hausa': 'ha',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Hiri Motu': 'ho',
    'Croatian': 'hr',
    'Haitian; Haitian Creole': 'ht',
    'Hungarian': 'hu',
    'Armenian': 'hy',
    'Herero': 'hz',
    'Interlingua (International Auxiliary Language Association)': 'ia',
    'Indonesian': 'id',
    'Interlingue; Occidental': 'ie',
    'Igbo': 'ig',
    'Sichuan Yi; Nuosu': 'ii',
    'Inupiaq': 'ik',
    'Ido': 'io',
    'Icelandic': 'is',
    'Italian': 'it',
    'Inuktitut': 'iu',
    'Japanese': 'ja',
    'Javanese': 'jv',
    'Georgian': 'ka',
    'Kongo': 'kg',
    'Kikuyu; Gikuyu': 'ki',
    'Kuanyama; Kwanyama': 'kj',
    'Kazakh': 'kk',
    'Kalaallisut; Greenlandic': 'kl',
    'Central Khmer': 'km',
    'Kannada': 'kn',
    'Korean': 'ko',
    'Kanuri': 'kr',
    'Kashmiri': 'ks',
    'Kurdish': 'ku',
    'Komi': 'kv',
    'Cornish': 'kw',
    'Kirghiz; Kyrgyz': 'ky',
    'Latin': 'la',
    'Luxembourgish; Letzeburgesch': 'lb',
    'Ganda': 'lg',
    'Limburgan; Limburger; Limburgish': 'li',
    'Lingala': 'ln',
    'Lao': 'lo',
    'Lithuanian': 'lt',
    'Luba-Katanga': 'lu',
    'Latvian': 'lv',
    'Malagasy': 'mg',
    'Marshallese': 'mh',
    'Maori': 'mi',
    'Macedonian': 'mk',
    'Malayalam': 'ml',
    'Mongolian': 'mn',
    'Marathi': 'mr',
    'Malay': 'ms',
    'Maltese': 'mt',
    'Burmese': 'my',
    'Nauru': 'na',
    'Bokmål, Norwegian; Norwegian Bokmål': 'nb',
    'Ndebele, North; North Ndebele': 'nd',
    'Nepali': 'ne',
    'Ndonga': 'ng',
    'Dutch; Flemish': 'nl',
    'Norwegian Nynorsk; Nynorsk, Norwegian': 'nn',
    'Norwegian': 'no',
    'Ndebele, South; South Ndebele': 'nr',
    'Navajo; Navaho': 'nv',
    'Chichewa; Chewa; Nyanja': 'ny',
    'Occitan (post 1500); Provençal': 'oc',
    'Ojibwa': 'oj',
    'Oromo': 'om',
    'Oriya': 'or',
    'Ossetian; Ossetic': 'os',
    'Panjabi; Punjabi': 'pa',
    'Pali': 'pi',
    'Polish': 'pl',
    'Pushto; Pashto': 'ps',
    'Portuguese': 'pt',
    'Quechua': 'qu',
    'Romansh': 'rm',
    'Rundi': 'rn',
    'Romanian; Moldavian; Moldovan': 'ro',
    'Russian': 'ru',
    'Kinyarwanda': 'rw',
    'Sanskrit': 'sa',
    'Sardinian': 'sc',
    'Sindhi': 'sd',
    'Northern Sami': 'se',
    'Sango': 'sg',
    'Sinhala; Sinhalese': 'si',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Samoan': 'sm',
    'Shona': 'sn',
    'Somali': 'so',
    'Albanian': 'sq',
    'Serbian': 'sr',
    'Swati': 'ss',
    'Sotho, Southern': 'st',
    'Sundanese': 'su',
    'Swedish': 'sv',
    'Swahili': 'sw',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Tajik': 'tg',
    'Thai': 'th',
    'Tigrinya': 'ti',
    'Turkmen': 'tk',
    'Tagalog': 'tl',
    'Tswana': 'tn',
    'Tonga (Tonga Islands)': 'to',
    'Turkish': 'tr',
    'Tsonga': 'ts',
    'Tatar': 'tt',
    'Twi': 'tw',
    'Tahitian': 'ty',
    'Uighur; Uyghur': 'ug',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
    'Uzbek': 'uz',
    'Venda': 've',
    'Vietnamese': 'vi',
    'Volapük': 'vo',
    'Walloon': 'wa',
    'Wolof': 'wo',
    'Xhosa': 'xh',
    'Yiddish': 'yi',
    'Yoruba': 'yo',
    'Zhuang; Chuang': 'za',
    'Chinese': 'zh',
    'Zulu': 'zu',
}

sort_directions = [
    "HybridRel",  # Default
    "DateDesc",
    "DateAsc",
    "ToneDesc",
    "ToneAsc"
]
