INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('aw', 'abw', '🇦🇼', 'Aruba', 'Aruba 🇦🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bs', 'bhs', '🇧🇸', 'Bahamas', 'Bahamas 🇧🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ba', 'bih', '🇧🇦', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina 🇧🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bl', 'blm', '🇧🇱', 'Saint Barthélemy', 'Saint Barthélemy 🇧🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('by', 'blr', '🇧🇾', 'Belarus', 'Belarus 🇧🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bz', 'blz', '🇧🇿', 'Belize', 'Belize 🇧🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bm', 'bmu', '🇧🇲', 'Bermuda', 'Bermuda 🇧🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bo', 'bol', '🇧🇴', 'Bolivia, Plurinational State of', 'Bolivia, Plurinational State of 🇧🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('br', 'bra', '🇧🇷', 'Brazil', 'Brazil 🇧🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bb', 'brb', '🇧🇧', 'Barbados', 'Barbados 🇧🇧');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bn', 'brn', '🇧🇳', 'Brunei Darussalam', 'Brunei Darussalam 🇧🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bt', 'btn', '🇧🇹', 'Bhutan', 'Bhutan 🇧🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bv', 'bvt', '🇧🇻', 'Bouvet Island', 'Bouvet Island 🇧🇻');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bw', 'bwa', '🇧🇼', 'Botswana', 'Botswana 🇧🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cf', 'caf', '🇨🇫', 'Central African Republic', 'Central African Republic 🇨🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ca', 'can', '🇨🇦', 'Canada', 'Canada 🇨🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cc', 'cck', '🇨🇨', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands 🇨🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ch', 'che', '🇨🇭', 'Switzerland', 'Switzerland 🇨🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cl', 'chl', '🇨🇱', 'Chile', 'Chile 🇨🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cn', 'chn', '🇨🇳', 'China', 'China 🇨🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ci', 'civ', '🇨🇮', 'Côte d''Ivoire', 'Côte d''Ivoire 🇨🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cm', 'cmr', '🇨🇲', 'Cameroon', 'Cameroon 🇨🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cd', 'cod', '🇨🇩', 'Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the 🇨🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cg', 'cog', '🇨🇬', 'Congo', 'Congo 🇨🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ck', 'cok', '🇨🇰', 'Cook Islands', 'Cook Islands 🇨🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('co', 'col', '🇨🇴', 'Colombia', 'Colombia 🇨🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('km', 'com', '🇰🇲', 'Comoros', 'Comoros 🇰🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cv', 'cpv', '🇨🇻', 'Cabo Verde', 'Cabo Verde 🇨🇻');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cr', 'cri', '🇨🇷', 'Costa Rica', 'Costa Rica 🇨🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cu', 'cub', '🇨🇺', 'Cuba', 'Cuba 🇨🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cw', 'cuw', '🇨🇼', 'Curaçao', 'Curaçao 🇨🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cx', 'cxr', '🇨🇽', 'Christmas Island', 'Christmas Island 🇨🇽');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ky', 'cym', '🇰🇾', 'Cayman Islands', 'Cayman Islands 🇰🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cy', 'cyp', '🇨🇾', 'Cyprus', 'Cyprus 🇨🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('cz', 'cze', '🇨🇿', 'Czechia', 'Czechia 🇨🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('de', 'deu', '🇩🇪', 'Germany', 'Germany 🇩🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('dj', 'dji', '🇩🇯', 'Djibouti', 'Djibouti 🇩🇯');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('dm', 'dma', '🇩🇲', 'Dominica', 'Dominica 🇩🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('dk', 'dnk', '🇩🇰', 'Denmark', 'Denmark 🇩🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('do', 'dom', '🇩🇴', 'Dominican Republic', 'Dominican Republic 🇩🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('dz', 'dza', '🇩🇿', 'Algeria', 'Algeria 🇩🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ec', 'ecu', '🇪🇨', 'Ecuador', 'Ecuador 🇪🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('eg', 'egy', '🇪🇬', 'Egypt', 'Egypt 🇪🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('er', 'eri', '🇪🇷', 'Eritrea', 'Eritrea 🇪🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('eh', 'esh', '🇪🇭', 'Western Sahara', 'Western Sahara 🇪🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('es', 'esp', '🇪🇸', 'Spain', 'Spain 🇪🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ee', 'est', '🇪🇪', 'Estonia', 'Estonia 🇪🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('et', 'eth', '🇪🇹', 'Ethiopia', 'Ethiopia 🇪🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('fi', 'fin', '🇫🇮', 'Finland', 'Finland 🇫🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('fj', 'fji', '🇫🇯', 'Fiji', 'Fiji 🇫🇯');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('fk', 'flk', '🇫🇰', 'Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas) 🇫🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('fr', 'fra', '🇫🇷', 'France', 'France 🇫🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('fo', 'fro', '🇫🇴', 'Faroe Islands', 'Faroe Islands 🇫🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('fm', 'fsm', '🇫🇲', 'Micronesia, Federated States of', 'Micronesia, Federated States of 🇫🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ga', 'gab', '🇬🇦', 'Gabon', 'Gabon 🇬🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gb', 'gbr', '🇬🇧', 'United Kingdom', 'United Kingdom 🇬🇧');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ge', 'geo', '🇬🇪', 'Georgia', 'Georgia 🇬🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gg', 'ggy', '🇬🇬', 'Guernsey', 'Guernsey 🇬🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gh', 'gha', '🇬🇭', 'Ghana', 'Ghana 🇬🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gi', 'gib', '🇬🇮', 'Gibraltar', 'Gibraltar 🇬🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gn', 'gin', '🇬🇳', 'Guinea', 'Guinea 🇬🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gp', 'glp', '🇬🇵', 'Guadeloupe', 'Guadeloupe 🇬🇵');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gm', 'gmb', '🇬🇲', 'Gambia', 'Gambia 🇬🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gw', 'gnb', '🇬🇼', 'Guinea-Bissau', 'Guinea-Bissau 🇬🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gq', 'gnq', '🇬🇶', 'Equatorial Guinea', 'Equatorial Guinea 🇬🇶');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gr', 'grc', '🇬🇷', 'Greece', 'Greece 🇬🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gd', 'grd', '🇬🇩', 'Grenada', 'Grenada 🇬🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gl', 'grl', '🇬🇱', 'Greenland', 'Greenland 🇬🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gt', 'gtm', '🇬🇹', 'Guatemala', 'Guatemala 🇬🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gf', 'guf', '🇬🇫', 'French Guiana', 'French Guiana 🇬🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gu', 'gum', '🇬🇺', 'Guam', 'Guam 🇬🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gy', 'guy', '🇬🇾', 'Guyana', 'Guyana 🇬🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('hk', 'hkg', '🇭🇰', 'Hong Kong', 'Hong Kong 🇭🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('hm', 'hmd', '🇭🇲', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands 🇭🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('hn', 'hnd', '🇭🇳', 'Honduras', 'Honduras 🇭🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('hr', 'hrv', '🇭🇷', 'Croatia', 'Croatia 🇭🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ht', 'hti', '🇭🇹', 'Haiti', 'Haiti 🇭🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('hu', 'hun', '🇭🇺', 'Hungary', 'Hungary 🇭🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('id', 'idn', '🇮🇩', 'Indonesia', 'Indonesia 🇮🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('im', 'imn', '🇮🇲', 'Isle of Man', 'Isle of Man 🇮🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('in', 'ind', '🇮🇳', 'India', 'India 🇮🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('io', 'iot', '🇮🇴', 'British Indian Ocean Territory', 'British Indian Ocean Territory 🇮🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ie', 'irl', '🇮🇪', 'Ireland', 'Ireland 🇮🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ir', 'irn', '🇮🇷', 'Iran, Islamic Republic of', 'Iran, Islamic Republic of 🇮🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('iq', 'irq', '🇮🇶', 'Iraq', 'Iraq 🇮🇶');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('is', 'isl', '🇮🇸', 'Iceland', 'Iceland 🇮🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('il', 'isr', '🇮🇱', 'Israel', 'Israel 🇮🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('it', 'ita', '🇮🇹', 'Italy', 'Italy 🇮🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('jm', 'jam', '🇯🇲', 'Jamaica', 'Jamaica 🇯🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('je', 'jey', '🇯🇪', 'Jersey', 'Jersey 🇯🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('jo', 'jor', '🇯🇴', 'Jordan', 'Jordan 🇯🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('jp', 'jpn', '🇯🇵', 'Japan', 'Japan 🇯🇵');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kz', 'kaz', '🇰🇿', 'Kazakhstan', 'Kazakhstan 🇰🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ke', 'ken', '🇰🇪', 'Kenya', 'Kenya 🇰🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kg', 'kgz', '🇰🇬', 'Kyrgyzstan', 'Kyrgyzstan 🇰🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kh', 'khm', '🇰🇭', 'Cambodia', 'Cambodia 🇰🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ki', 'kir', '🇰🇮', 'Kiribati', 'Kiribati 🇰🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kn', 'kna', '🇰🇳', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis 🇰🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kr', 'kor', '🇰🇷', 'Korea, Republic of', 'Korea, Republic of 🇰🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('af', 'afg', '🇦🇫', 'Afghanistan', 'Afghanistan 🇦🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ao', 'ago', '🇦🇴', 'Angola', 'Angola 🇦🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ai', 'aia', '🇦🇮', 'Anguilla', 'Anguilla 🇦🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ax', 'ala', '🇦🇽', 'Åland Islands', 'Åland Islands 🇦🇽');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('al', 'alb', '🇦🇱', 'Albania', 'Albania 🇦🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ad', 'and', '🇦🇩', 'Andorra', 'Andorra 🇦🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ae', 'are', '🇦🇪', 'United Arab Emirates', 'United Arab Emirates 🇦🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ar', 'arg', '🇦🇷', 'Argentina', 'Argentina 🇦🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('am', 'arm', '🇦🇲', 'Armenia', 'Armenia 🇦🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('as', 'asm', '🇦🇸', 'American Samoa', 'American Samoa 🇦🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('aq', 'ata', '🇦🇶', 'Antarctica', 'Antarctica 🇦🇶');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tf', 'atf', '🇹🇫', 'French Southern Territories', 'French Southern Territories 🇹🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ag', 'atg', '🇦🇬', 'Antigua and Barbuda', 'Antigua and Barbuda 🇦🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('au', 'aus', '🇦🇺', 'Australia', 'Australia 🇦🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('at', 'aut', '🇦🇹', 'Austria', 'Austria 🇦🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('az', 'aze', '🇦🇿', 'Azerbaijan', 'Azerbaijan 🇦🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bi', 'bdi', '🇧🇮', 'Burundi', 'Burundi 🇧🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('be', 'bel', '🇧🇪', 'Belgium', 'Belgium 🇧🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bj', 'ben', '🇧🇯', 'Benin', 'Benin 🇧🇯');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bq', 'bes', '🇧🇶', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba 🇧🇶');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bf', 'bfa', '🇧🇫', 'Burkina Faso', 'Burkina Faso 🇧🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bd', 'bgd', '🇧🇩', 'Bangladesh', 'Bangladesh 🇧🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bg', 'bgr', '🇧🇬', 'Bulgaria', 'Bulgaria 🇧🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('bh', 'bhr', '🇧🇭', 'Bahrain', 'Bahrain 🇧🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kw', 'kwt', '🇰🇼', 'Kuwait', 'Kuwait 🇰🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('la', 'lao', '🇱🇦', 'Lao People''s Democratic Republic', 'Lao People''s Democratic Republic 🇱🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lb', 'lbn', '🇱🇧', 'Lebanon', 'Lebanon 🇱🇧');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lr', 'lbr', '🇱🇷', 'Liberia', 'Liberia 🇱🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ly', 'lby', '🇱🇾', 'Libya', 'Libya 🇱🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lc', 'lca', '🇱🇨', 'Saint Lucia', 'Saint Lucia 🇱🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('li', 'lie', '🇱🇮', 'Liechtenstein', 'Liechtenstein 🇱🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lk', 'lka', '🇱🇰', 'Sri Lanka', 'Sri Lanka 🇱🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ls', 'lso', '🇱🇸', 'Lesotho', 'Lesotho 🇱🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lt', 'ltu', '🇱🇹', 'Lithuania', 'Lithuania 🇱🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lu', 'lux', '🇱🇺', 'Luxembourg', 'Luxembourg 🇱🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('lv', 'lva', '🇱🇻', 'Latvia', 'Latvia 🇱🇻');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mo', 'mac', '🇲🇴', 'Macao', 'Macao 🇲🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mf', 'maf', '🇲🇫', 'Saint Martin (French part)', 'Saint Martin (French part) 🇲🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ma', 'mar', '🇲🇦', 'Morocco', 'Morocco 🇲🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mc', 'mco', '🇲🇨', 'Monaco', 'Monaco 🇲🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('md', 'mda', '🇲🇩', 'Moldova, Republic of', 'Moldova, Republic of 🇲🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mg', 'mdg', '🇲🇬', 'Madagascar', 'Madagascar 🇲🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mv', 'mdv', '🇲🇻', 'Maldives', 'Maldives 🇲🇻');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mx', 'mex', '🇲🇽', 'Mexico', 'Mexico 🇲🇽');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mh', 'mhl', '🇲🇭', 'Marshall Islands', 'Marshall Islands 🇲🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mk', 'mkd', '🇲🇰', 'North Macedonia', 'North Macedonia 🇲🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ml', 'mli', '🇲🇱', 'Mali', 'Mali 🇲🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mt', 'mlt', '🇲🇹', 'Malta', 'Malta 🇲🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mm', 'mmr', '🇲🇲', 'Myanmar', 'Myanmar 🇲🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('me', 'mne', '🇲🇪', 'Montenegro', 'Montenegro 🇲🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mn', 'mng', '🇲🇳', 'Mongolia', 'Mongolia 🇲🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mp', 'mnp', '🇲🇵', 'Northern Mariana Islands', 'Northern Mariana Islands 🇲🇵');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mz', 'moz', '🇲🇿', 'Mozambique', 'Mozambique 🇲🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mr', 'mrt', '🇲🇷', 'Mauritania', 'Mauritania 🇲🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ms', 'msr', '🇲🇸', 'Montserrat', 'Montserrat 🇲🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mq', 'mtq', '🇲🇶', 'Martinique', 'Martinique 🇲🇶');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mu', 'mus', '🇲🇺', 'Mauritius', 'Mauritius 🇲🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('mw', 'mwi', '🇲🇼', 'Malawi', 'Malawi 🇲🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('my', 'mys', '🇲🇾', 'Malaysia', 'Malaysia 🇲🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('yt', 'myt', '🇾🇹', 'Mayotte', 'Mayotte 🇾🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('na', 'nam', '🇳🇦', 'Namibia', 'Namibia 🇳🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('nc', 'ncl', '🇳🇨', 'New Caledonia', 'New Caledonia 🇳🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ne', 'ner', '🇳🇪', 'Niger', 'Niger 🇳🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('nf', 'nfk', '🇳🇫', 'Norfolk Island', 'Norfolk Island 🇳🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ng', 'nga', '🇳🇬', 'Nigeria', 'Nigeria 🇳🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ni', 'nic', '🇳🇮', 'Nicaragua', 'Nicaragua 🇳🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sv', 'slv', '🇸🇻', 'El Salvador', 'El Salvador 🇸🇻');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sm', 'smr', '🇸🇲', 'San Marino', 'San Marino 🇸🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('so', 'som', '🇸🇴', 'Somalia', 'Somalia 🇸🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pm', 'spm', '🇵🇲', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon 🇵🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('rs', 'srb', '🇷🇸', 'Serbia', 'Serbia 🇷🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ss', 'ssd', '🇸🇸', 'South Sudan', 'South Sudan 🇸🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('st', 'stp', '🇸🇹', 'Sao Tome and Principe', 'Sao Tome and Principe 🇸🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sr', 'sur', '🇸🇷', 'Suriname', 'Suriname 🇸🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sk', 'svk', '🇸🇰', 'Slovakia', 'Slovakia 🇸🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('si', 'svn', '🇸🇮', 'Slovenia', 'Slovenia 🇸🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('se', 'swe', '🇸🇪', 'Sweden', 'Sweden 🇸🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sz', 'swz', '🇸🇿', 'Eswatini', 'Eswatini 🇸🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sx', 'sxm', '🇸🇽', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part) 🇸🇽');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sc', 'syc', '🇸🇨', 'Seychelles', 'Seychelles 🇸🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sy', 'syr', '🇸🇾', 'Syrian Arab Republic', 'Syrian Arab Republic 🇸🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('nu', 'niu', '🇳🇺', 'Niue', 'Niue 🇳🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('nl', 'nld', '🇳🇱', 'Netherlands', 'Netherlands 🇳🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('no', 'nor', '🇳🇴', 'Norway', 'Norway 🇳🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('np', 'npl', '🇳🇵', 'Nepal', 'Nepal 🇳🇵');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('nr', 'nru', '🇳🇷', 'Nauru', 'Nauru 🇳🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('nz', 'nzl', '🇳🇿', 'New Zealand', 'New Zealand 🇳🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('om', 'omn', '🇴🇲', 'Oman', 'Oman 🇴🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pk', 'pak', '🇵🇰', 'Pakistan', 'Pakistan 🇵🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pa', 'pan', '🇵🇦', 'Panama', 'Panama 🇵🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pn', 'pcn', '🇵🇳', 'Pitcairn', 'Pitcairn 🇵🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pe', 'per', '🇵🇪', 'Peru', 'Peru 🇵🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ph', 'phl', '🇵🇭', 'Philippines', 'Philippines 🇵🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pw', 'plw', '🇵🇼', 'Palau', 'Palau 🇵🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pg', 'png', '🇵🇬', 'Papua New Guinea', 'Papua New Guinea 🇵🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pl', 'pol', '🇵🇱', 'Poland', 'Poland 🇵🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pr', 'pri', '🇵🇷', 'Puerto Rico', 'Puerto Rico 🇵🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('kp', 'prk', '🇰🇵', 'Korea, Democratic People''s Republic of', 'Korea, Democratic People''s Republic of 🇰🇵');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pt', 'prt', '🇵🇹', 'Portugal', 'Portugal 🇵🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('py', 'pry', '🇵🇾', 'Paraguay', 'Paraguay 🇵🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ps', 'pse', '🇵🇸', 'Palestine, State of', 'Palestine, State of 🇵🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('pf', 'pyf', '🇵🇫', 'French Polynesia', 'French Polynesia 🇵🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('qa', 'qat', '🇶🇦', 'Qatar', 'Qatar 🇶🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('re', 'reu', '🇷🇪', 'Réunion', 'Réunion 🇷🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ro', 'rou', '🇷🇴', 'Romania', 'Romania 🇷🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ru', 'rus', '🇷🇺', 'Russian Federation', 'Russian Federation 🇷🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('rw', 'rwa', '🇷🇼', 'Rwanda', 'Rwanda 🇷🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sa', 'sau', '🇸🇦', 'Saudi Arabia', 'Saudi Arabia 🇸🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sd', 'sdn', '🇸🇩', 'Sudan', 'Sudan 🇸🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sn', 'sen', '🇸🇳', 'Senegal', 'Senegal 🇸🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sg', 'sgp', '🇸🇬', 'Singapore', 'Singapore 🇸🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('gs', 'sgs', '🇬🇸', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands 🇬🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sh', 'shn', '🇸🇭', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha 🇸🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sj', 'sjm', '🇸🇯', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen 🇸🇯');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sb', 'slb', '🇸🇧', 'Solomon Islands', 'Solomon Islands 🇸🇧');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('sl', 'sle', '🇸🇱', 'Sierra Leone', 'Sierra Leone 🇸🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tc', 'tca', '🇹🇨', 'Turks and Caicos Islands', 'Turks and Caicos Islands 🇹🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('td', 'tcd', '🇹🇩', 'Chad', 'Chad 🇹🇩');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tg', 'tgo', '🇹🇬', 'Togo', 'Togo 🇹🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('th', 'tha', '🇹🇭', 'Thailand', 'Thailand 🇹🇭');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tj', 'tjk', '🇹🇯', 'Tajikistan', 'Tajikistan 🇹🇯');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tk', 'tkl', '🇹🇰', 'Tokelau', 'Tokelau 🇹🇰');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tm', 'tkm', '🇹🇲', 'Turkmenistan', 'Turkmenistan 🇹🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tl', 'tls', '🇹🇱', 'Timor-Leste', 'Timor-Leste 🇹🇱');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('to', 'ton', '🇹🇴', 'Tonga', 'Tonga 🇹🇴');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tt', 'tto', '🇹🇹', 'Trinidad and Tobago', 'Trinidad and Tobago 🇹🇹');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tn', 'tun', '🇹🇳', 'Tunisia', 'Tunisia 🇹🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tr', 'tur', '🇹🇷', 'Turkey', 'Turkey 🇹🇷');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tv', 'tuv', '🇹🇻', 'Tuvalu', 'Tuvalu 🇹🇻');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tw', 'twn', '🇹🇼', 'Taiwan, Province of China', 'Taiwan, Province of China 🇹🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('tz', 'tza', '🇹🇿', 'Tanzania, United Republic of', 'Tanzania, United Republic of 🇹🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ug', 'uga', '🇺🇬', 'Uganda', 'Uganda 🇺🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ua', 'ukr', '🇺🇦', 'Ukraine', 'Ukraine 🇺🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('um', 'umi', '🇺🇲', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands 🇺🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('uy', 'ury', '🇺🇾', 'Uruguay', 'Uruguay 🇺🇾');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('us', 'usa', '🇺🇸', 'United States', 'United States 🇺🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('uz', 'uzb', '🇺🇿', 'Uzbekistan', 'Uzbekistan 🇺🇿');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('va', 'vat', '🇻🇦', 'Holy See (Vatican City State)', 'Holy See (Vatican City State) 🇻🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('vc', 'vct', '🇻🇨', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines 🇻🇨');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ve', 'ven', '🇻🇪', 'Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of 🇻🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('vg', 'vgb', '🇻🇬', 'Virgin Islands, British', 'Virgin Islands, British 🇻🇬');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('vi', 'vir', '🇻🇮', 'Virgin Islands, U.S.', 'Virgin Islands, U.S. 🇻🇮');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('vn', 'vnm', '🇻🇳', 'Viet Nam', 'Viet Nam 🇻🇳');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('vu', 'vut', '🇻🇺', 'Vanuatu', 'Vanuatu 🇻🇺');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('wf', 'wlf', '🇼🇫', 'Wallis and Futuna', 'Wallis and Futuna 🇼🇫');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ws', 'wsm', '🇼🇸', 'Samoa', 'Samoa 🇼🇸');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('ye', 'yem', '🇾🇪', 'Yemen', 'Yemen 🇾🇪');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('za', 'zaf', '🇿🇦', 'South Africa', 'South Africa 🇿🇦');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('zm', 'zmb', '🇿🇲', 'Zambia', 'Zambia 🇿🇲');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('zw', 'zwe', '🇿🇼', 'Zimbabwe', 'Zimbabwe 🇿🇼');
INSERT INTO public.countries (alpha_2, alpha_3, flag, name, description) VALUES ('eu', 'eu', '🇪🇺', 'European Union', 'European Union 🇪🇺');
